[options]
admin_passwd = $pbkdf2-sha512$600000$1ToHAKCU0tq7t3aOMQYgpA$U6NoogjggAr5YEGKa6low.3kZtxcUYE10bnZGgB/Xxp.lUIDJAWOVc3Aa.USFjbM.AeyPrFoT3k.SUUIO404hQ
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
proxy_mode = True

