[options]
admin_passwd = $pbkdf2-sha512$600000$4jyHEGKM8b6Xsra2FkLI2Q$MHSKp2CtWw3LkHtbazckwCq3jewX1H3SJhHmGR1bFSgzPv6vYIGYy1kNvN3PAXu3YqU0KJLvgMWShvyaabaJfQ
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
proxy_mode = True

